# numpy get started
导入numpy库，并查看numpy版本

In [1]:
import numpy as np

In [2]:
np.__version__

'1.19.1'

In [4]:
import pandas as pd

In [5]:
pd.__version__

'1.0.5'

In [6]:
import requests

In [7]:
requests.__version__

'2.24.0'

一、创建ndarray
1. 使用np.array()由python list创建
参数为列表： [1, 4, 2, 5, 3]

注意：

numpy默认ndarray的所有元素的类型是相同的
如果传进来的列表中包含不同的类型，则统一为同一类型，优先级：str>float>int

In [8]:
l = [1,2,3,4,5,9,8,7,6]
l

[1, 2, 3, 4, 5, 9, 8, 7, 6]

In [10]:
type(l)

list

In [11]:
nd = np.array(l)
nd

array([1, 2, 3, 4, 5, 9, 8, 7, 6])

In [12]:
type(nd)

numpy.ndarray

In [13]:
l2 = [[1,3,5,7],[2,4,6,8]]
l2

[[1, 3, 5, 7], [2, 4, 6, 8]]

In [14]:
nd2 = np.array(l2)
nd2

array([[1, 3, 5, 7],
       [2, 4, 6, 8]])

In [15]:
nd.sum()

45

In [16]:
nd.var()

6.666666666666667

In [20]:
nd = np.random.normal(loc = 175,scale=10,size = 10000).round(2)
nd

array([180.02, 162.26, 184.18, ..., 179.19, 182.83, 174.51])

In [22]:
np.random.random(10)

array([0.80403643, 0.60631454, 0.22301424, 0.03813725, 0.14537585,
       0.00946211, 0.39063408, 0.5558176 , 0.39426771, 0.74874309])

In [25]:
nd5 = np.random.randint(0,100,size=(6,5))
nd5

array([[ 2, 47, 19, 21, 27],
       [21, 66, 29, 86, 48],
       [12, 78, 87, 82, 90],
       [87, 21,  3, 56, 78],
       [ 7, 18,  8, 64, 95],
       [46,  2, 62, 36, 11]])

In [28]:
np.hsplit(nd5,indices_or_sections=[3])

[array([[ 2, 47, 19],
        [21, 66, 29],
        [12, 78, 87],
        [87, 21,  3],
        [ 7, 18,  8],
        [46,  2, 62]]),
 array([[21, 27],
        [86, 48],
        [82, 90],
        [56, 78],
        [64, 95],
        [36, 11]])]

In [29]:
nd7 = nd5

In [30]:
id(nd7)

2174915628688

In [31]:
id(nd5)

2174915628688

In [32]:
nd8 = nd5.copy()

In [33]:
id(nd8)

2174923593888