# numpy get started

导入numpy库，并查看numpy版本

In [1]:
import numpy as np

In [2]:
np.__version__

'1.19.1'

In [3]:
import pandas as pd

In [4]:
pd.__version__

'1.0.5'

In [5]:
import requests as requests

In [6]:
requests.__version__

'2.24.0'

## 一、创建ndarray

### 1. 使用np.array()由python list创建

参数为列表：
[1, 4, 2, 5, 3]

注意：
- numpy默认ndarray的所有元素的类型是相同的
- 如果传进来的列表中包含不同的类型，则统一为同一类型，优先级：str>float>int

In [7]:
l = [1,2,3,4,5,9,8,7,6]
l

[1, 2, 3, 4, 5, 9, 8, 7, 6]

In [8]:
l.sum()

AttributeError: 'list' object has no attribute 'sum'

In [ ]:
type(l)

In [ ]:
nd = np.array(l)
nd

In [ ]:
type(nd)

In [ ]:
l2 = [[1,3,5,7],[2,4,6,8]]
l2

In [ ]:
nd2 = np.array(l2)
nd2

In [ ]:
nd.sum()

In [ ]:
nd.var()

In [ ]:
x = np.arange(0,100000,1)
x

In [ ]:
%timeit x.sum()

In [ ]:
# Python代码
def sum2(x):
    ret = 0
    for i in x:
        ret += i
    return ret

In [ ]:
%timeit sum2(x)

### 2. 使用np的routines函数创建

包含以下常见创建方法：

1) np.ones(shape, dtype=None, order='C')

In [ ]:
np.ones(shape = (5,5),dtype=np.int8)

2) np.zeros(shape, dtype=float, order='C')

In [ ]:
np.zeros(shape = (2,3,4),dtype=np.float16)

3) np.full(shape, fill_value, dtype=None, order='C')

In [ ]:
np.full(shape = (3,5),fill_value=3.14)

4) np.eye(N, M=None, k=0, dtype=float)  
对角线为1其他的位置为0

In [ ]:
# 单位矩阵
np.eye(N = 5)

5) np.linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None)

In [ ]:
# 等差数列
np.linspace(0,100,num = 21)

6) np.arange([start, ]stop, [step, ]dtype=None)

In [ ]:
np.arange(0,100,3)

7) np.random.randint(low, high=None, size=None, dtype='l')

In [ ]:
np.random.randint(0,100,size = (5,5))

8) np.random.randn(d0, d1, ..., dn)  

标准正太分布

In [ ]:
# normal 正常，正太
# dimession 维度
# 平均值是0，方差是1
np.random.randn(4,5)

9)np.random.normal(loc=0.0, scale=1.0, size=None)

In [13]:
nd = np.random.normal(loc = 175,scale=10,size = 10000).round(2)
nd

array([189.04, 166.26, 172.39, ..., 172.82, 166.85, 165.64])

In [14]:
nd.mean()

174.946112

In [15]:
nd.var()

98.943717863456

In [16]:
# 标准差，是方差的开平发
nd.std()

9.947045685200003

10) np.random.random(size=None)  

生成0到1的随机数，左闭右开

In [ ]:
np.random.random(100)

#使用随机数成成一张图片

## 二、ndarray的属性

4个必记参数：
ndim：维度
shape：形状（各维度的长度）
size：总长度

dtype：元素类型


In [ ]:
nd

In [ ]:
nd.size

In [ ]:
nd.shape

In [ ]:
nd.ndim

In [ ]:
nd.dtype

## 三、ndarray的基本操作

### 1. 索引
一维与列表完全一致
多维时同理

In [17]:
nd2 = np.random.randint(0,150,size = (4,5))
nd2

array([[124,  91,  52,  23,  16],
       [122, 106, 143,  88,  85],
       [100,   0, 141, 101,  72],
       [ 26,  93, 123,   4,  31]])

In [18]:
nd2[1,1]

106

In [19]:
nd2[2]

array([100,   0, 141, 101,  72])

根据索引修改数据

### 2. 切片
一维与列表完全一致
多维时同理

In [20]:
nd2

array([[124,  91,  52,  23,  16],
       [122, 106, 143,  88,  85],
       [100,   0, 141, 101,  72],
       [ 26,  93, 123,   4,  31]])

In [21]:
nd2[0:3]

array([[124,  91,  52,  23,  16],
       [122, 106, 143,  88,  85],
       [100,   0, 141, 101,  72]])

In [22]:
nd2[-2:]

array([[100,   0, 141, 101,  72],
       [ 26,  93, 123,   4,  31]])

In [23]:
nd2[0:3,0:3]

array([[124,  91,  52],
       [122, 106, 143],
       [100,   0, 141]])

将数据反转，例如[1,2,3]---->[3,2,1]

In [24]:
nd3 = nd[:10]
nd3

array([189.04, 166.26, 172.39, 172.1 , 173.  , 176.82, 176.  , 177.74,
       162.46, 176.13])

In [25]:
nd3[::-1]

array([176.13, 162.46, 177.74, 176.  , 176.82, 173.  , 172.1 , 172.39,
       166.26, 189.04])

两个::进行切片

In [ ]:
nd3[::2]

In [ ]:
from PIL import Image

In [ ]:
cat = Image.open('./cat.jpg')
cat

In [ ]:
cat_data = np.array(cat)
# 图片数据是 ndarray
# 彩色图片三维：高度，宽度，像素（表示不同颜色），红绿蓝三原色，搭配可以变幻出世界上任何颜色
cat_data

In [ ]:
# 行，列，像素
cat_data.shape

In [ ]:
cat_data.dtype

In [ ]:
2**8

In [ ]:
# int8 从-128 ~ 127

In [ ]:
np.int8(128)

In [ ]:
cat_data.max()

In [ ]:
cat_data.min()

In [ ]:
cat_data

In [ ]:
cat2 = cat_data[:,:,::-1]
cat2

In [ ]:
Image.fromarray(cat2)

In [ ]:
Image.fromarray(cat_data[::5,::5])

In [ ]:
#  红绿蓝 0,1,2
# 绿红蓝 1,0,2
Image.fromarray(cat_data[:,:,[1,0,2]])

In [ ]:
cat4 = cat_data[:,:,0]
Image.fromarray(cat4)

In [ ]:
import matplotlib.pyplot as plt
%matplotlib inline

In [ ]:
plt.imshow(cat_data)

In [ ]:
plt.imshow(cat_data[::-1])

In [ ]:
plt.imshow(cat_data[::-15,::-15])

### 3. 变形
使用reshape函数，注意参数是一个tuple！

In [26]:
nd2

array([[124,  91,  52,  23,  16],
       [122, 106, 143,  88,  85],
       [100,   0, 141, 101,  72],
       [ 26,  93, 123,   4,  31]])

In [27]:
nd2.reshape(2,10)

array([[124,  91,  52,  23,  16, 122, 106, 143,  88,  85],
       [100,   0, 141, 101,  72,  26,  93, 123,   4,  31]])

In [28]:
nd2.reshape(5,4)

array([[124,  91,  52,  23],
       [ 16, 122, 106, 143],
       [ 88,  85, 100,   0],
       [141, 101,  72,  26],
       [ 93, 123,   4,  31]])

In [29]:
cat_data.shape

NameError: name 'cat_data' is not defined

In [30]:
cat5 = cat_data.reshape(730,456,3)
plt.imshow(cat5)

NameError: name 'cat_data' is not defined

In [ ]:
# 高度 0、宽度 1、像素 2
# 转置，行和列调整
cat6 = np.transpose(cat_data,axes = (1,0,2))
plt.imshow(cat6)

### 4. 级联
1. np.concatenate()
级联需要注意的点：
- 级联的参数是列表：一定要加中括号或小括号
- 维度必须相同
- 形状相符
- 【重点】级联的方向默认是shape这个tuple的第一个值所代表的维度方向
- 可通过axis参数改变级联的方向

In [31]:
nd2

array([[124,  91,  52,  23,  16],
       [122, 106, 143,  88,  85],
       [100,   0, 141, 101,  72],
       [ 26,  93, 123,   4,  31]])

In [32]:
np.concatenate([nd2,nd2])

array([[124,  91,  52,  23,  16],
       [122, 106, 143,  88,  85],
       [100,   0, 141, 101,  72],
       [ 26,  93, 123,   4,  31],
       [124,  91,  52,  23,  16],
       [122, 106, 143,  88,  85],
       [100,   0, 141, 101,  72],
       [ 26,  93, 123,   4,  31]])

In [ ]:
plt.imshow(cat_data)

In [ ]:
cat7 = cat_data[:,:230]
plt.imshow(cat7)

In [ ]:
cat8 = cat_data[:,470:,::-1]
plt.imshow(cat8)

In [ ]:
print(cat7.shape,cat8.shape)

In [ ]:
np.concatenate([cat7,cat8])

In [ ]:
display(cat7.shape,cat8.shape)

In [ ]:
# 高度 0 ，宽度 1，像素 2

In [ ]:
cat9 = np.concatenate([cat7,cat8],axis = 1)

In [ ]:
plt.imshow(cat9)

2. np.hstack与np.vstack  
水平级联与垂直级联,处理自己，进行维度的变更

In [ ]:
import numpy as np



In [44]:
nd1 = np.random.randint(0,150,size = (4,5))

nd2 = np.random.randint(0,150,size = (2,5))

nd3 = np.random.randint(0,150,size = (4,8))

display(nd1,nd2,nd3)

array([[ 64,  14, 132,   3,  19],
       [ 42,  79,  61, 142,  48],
       [ 38,  93, 149, 120,  36],
       [ 21,   6,  98,  67,  38]])

array([[113,  15,   9,  31,  22],
       [  3,  94,  60, 116,  79]])

array([[137,  13, 104,   7,  43, 136, 147,  12],
       [ 19,  36,  98,  39,  72,  38,  47, 128],
       [ 89, 149, 123, 149,  20,  73,  81,   6],
       [100,   6, 138, 127, 104,  28,  31,  61]])

In [46]:
np.concatenate([nd1,nd3],axis = 1)

array([[ 64,  14, 132,   3,  19, 137,  13, 104,   7,  43, 136, 147,  12],
       [ 42,  79,  61, 142,  48,  19,  36,  98,  39,  72,  38,  47, 128],
       [ 38,  93, 149, 120,  36,  89, 149, 123, 149,  20,  73,  81,   6],
       [ 21,   6,  98,  67,  38, 100,   6, 138, 127, 104,  28,  31,  61]])

In [47]:
# horizontal 水平的，列数增加
nd5 = np.hstack((nd1,nd3))

In [48]:
# vertical 竖直方向增多，行数增多
nd4 = np.vstack((nd1,nd2))

### 5. 切分

与级联类似，三个函数完成切分工作：
- np.split
- np.vsplit
- np.hsplit

In [49]:
nd4.shape

(6, 5)

In [50]:
nd4

array([[ 64,  14, 132,   3,  19],
       [ 42,  79,  61, 142,  48],
       [ 38,  93, 149, 120,  36],
       [ 21,   6,  98,  67,  38],
       [113,  15,   9,  31,  22],
       [  3,  94,  60, 116,  79]])

In [51]:
np.split(nd4,indices_or_sections=3)

[array([[ 64,  14, 132,   3,  19],
        [ 42,  79,  61, 142,  48]]),
 array([[ 38,  93, 149, 120,  36],
        [ 21,   6,  98,  67,  38]]),
 array([[113,  15,   9,  31,  22],
        [  3,  94,  60, 116,  79]])]

In [52]:
np.split(nd4,indices_or_sections=[1,3])

[array([[ 64,  14, 132,   3,  19]]),
 array([[ 42,  79,  61, 142,  48],
        [ 38,  93, 149, 120,  36]]),
 array([[ 21,   6,  98,  67,  38],
        [113,  15,   9,  31,  22],
        [  3,  94,  60, 116,  79]])]

In [61]:
np.vsplit(nd4,indices_or_sections=2)

[array([[ 64,  14, 132,   3,  19],
        [ 42,  79,  61, 142,  48],
        [ 38,  93, 149, 120,  36]]),
 array([[ 21,   6,  98,  67,  38],
        [113,  15,   9,  31,  22],
        [  3,  94,  60, 116,  79]])]

In [54]:
nd5.shape

(4, 13)

In [55]:
np.hsplit(nd5,indices_or_sections=[5])

[array([[ 64,  14, 132,   3,  19],
        [ 42,  79,  61, 142,  48],
        [ 38,  93, 149, 120,  36],
        [ 21,   6,  98,  67,  38]]),
 array([[137,  13, 104,   7,  43, 136, 147,  12],
        [ 19,  36,  98,  39,  72,  38,  47, 128],
        [ 89, 149, 123, 149,  20,  73,  81,   6],
        [100,   6, 138, 127, 104,  28,  31,  61]])]

### 6. 副本
所有赋值运算不会为ndarray的任何元素创建副本。对赋值后的对象的操作也对原来的对象生效。

可使用copy()函数创建副本

In [63]:
nd7 = nd5

In [ ]:
id(nd7)

In [ ]:
id(nd5)

In [ ]:
nd8 = nd5.copy()

In [ ]:
print(id(nd8))

## 四、ndarray的聚合操作

### 1. 求和np.sum

In [ ]:
nd5

In [ ]:
nd5.sum()

### 2. 最大最小值：np.max/ np.min
同理

In [ ]:
nd1

In [ ]:
nd1.prod()

In [ ]:
nd1[0].prod()

In [ ]:
nd1 = np.random.randint(0,10,size = (4,5))
nd1

In [ ]:
nd1.mean(axis = 1)

In [ ]:
nd1.mean(axis = 0)

In [ ]:
nd1.shape

### 3. 其他聚合操作
    Function Name	NaN-safe Version	Description
    np.sum	np.nansum	Compute sum of elements
    np.prod	np.nanprod	Compute product of elements
    np.mean	np.nanmean	Compute mean of elements
    np.std	np.nanstd	Compute standard deviation
    np.var	np.nanvar	Compute variance
    np.min	np.nanmin	Find minimum value
    np.max	np.nanmax	Find maximum value
    np.argmin	np.nanargmin	Find index of minimum value
    np.argmax	np.nanargmax	Find index of maximum value
    np.median	np.nanmedian	Compute median of elements
    np.percentile	np.nanpercentile	Compute rank-based statistics of elements
    np.any	N/A	Evaluate whether any elements are true
    np.all	N/A	Evaluate whether all elements are true
    np.power 幂运算

In [ ]:
np.sin(0)

In [ ]:
np.pi/2

In [ ]:
np.sin(np.pi/2)

In [ ]:
np.arcsin(1.0)

In [ ]:
np.arcsin(0.5)/np.pi*180

In [ ]:
nd4 = nd3.ravel()
nd4

In [ ]:
nd4

In [ ]:
np.log10(nd4)

In [ ]:
# 指数e
np.exp(2)

In [ ]:
2.718**2

In [ ]:
x + y = 10

In [ ]:
nd4.mean()

In [ ]:
nd4.median()

In [ ]:
# 具体对象没有该方法，模块方法
np.median(nd4)

In [ ]:
nd4

In [ ]:
nd4.sort()

In [ ]:
nd4

In [ ]:
np.median(nd4)

In [ ]:
np.percentile(nd4,q = 0)

In [ ]:
# 中位数，数据从小到大排列，取正中间



In [ ]:

nd2

In [ ]:
nd2.argmax()

In [ ]:
nd2.argmax(axis = 1)

In [ ]:
nd2.argmax(axis = -1)

In [ ]:
index = np.argwhere((nd2 > 50)&(nd2<100))
index

In [ ]:
nd2[1,2]

In [ ]:
for x,y in index:
    print(nd2[x,y])

In [ ]:
nd4

In [ ]:
nd4.any()

In [9]:
nd4.all()

NameError: name 'nd4' is not defined

In [ ]:
nd4[0] = 0
nd4

In [ ]:
nd4.all()

In [ ]:
nd4.any()

np.sum 和 np.nansum 的区别
nan not a number

In [ ]:
# 空值
a = np.array([1,3,5,7,9,11,np.NAN])
a

In [ ]:
a.sum()

In [ ]:
np.nansum(a)

In [ ]:
a.var()

In [ ]:
np.nanvar(a)

In [ ]:
a[-1] = 13
a

In [ ]:
b = a + 10
b

In [ ]:
np.corrcoef(a,b)

In [ ]:
c = a + np.random.randint(1,5,size = 7)
c

In [ ]:
np.corrcoef(a,c)

In [ ]:
d = a * -1

In [ ]:
d

In [ ]:
np.corrcoef(a,d)

In [ ]:
a

In [ ]:
f = np.ones(7)
f

In [ ]:
f[::2] = -1
f

In [ ]:
f.std()

In [ ]:
np.corrcoef(a,f)

In [ ]:
np.corrcoef(a,f)

In [ ]:
nd = np.random.randint(0,1000,size = 100)
nd

In [ ]:
nd.max()

In [ ]:
np.argwhere(nd <=112)

In [ ]:
# 直方图，统计数据出现的频次
np.histogram(nd,bins = 10)

In [ ]:
python = np.random.randint(0,151,size = 120)
python

In [ ]:
np.histogram(python,bins=5,range=[0,150])

In [ ]:
nd

In [ ]:
np.save('./data.npy',nd)

In [ ]:
np.load('./data.npy')

In [ ]:
3.49e2

In [ ]:
np.savetxt('./data.txt',nd)

In [ ]:
np.loadtxt('./data.txt')

#### 操作文件

使用pandas打开文件president_heights.csv
获取文件中的数据

## 五、ndarray的矩阵操作

### 1. 基本矩阵操作

1) 算术运算符：
- 加减乘除

2) 矩阵积np.dot()

In [ ]:
# x ,y ,z = 2,1,5

x + y + z = 8

2x - y + z = 8

3x + y - z = 2

In [ ]:
X = np.array([[1,1,1],[2,-1,1],[3,1,-1]])
X

In [ ]:
Y = np.array([8,8,2])
Y

In [ ]:
# w是我们要求解未知数
w = np.array(['x','y','z'])
w

In [ ]:
# 矩阵运算
Xw = Y

In [ ]:
# 逆矩阵
X_inv = np.linalg.inv(X)
X_inv

In [ ]:
np.dot(X_inv,Y)

In [ ]:
# 矩阵  逆矩阵（倒数关系），5 1/5

### 2. 广播机制

【重要】ndarray广播机制的两条规则
- 规则一：为缺失的维度补1
- 规则二：假定缺失元素用已有值填充


例1：
m = np.ones((2, 3))
a = np.arange(3)
求M+a

In [ ]:
nd + 10

In [ ]:
nd2 = nd.reshape(20,5)
nd2

In [ ]:
nd3 = np.arange(5)
nd3

In [ ]:
nd2 + nd3

In [ ]:
np.add(nd2,nd3)

In [ ]:
nd4 = np.random.randint(0,10,size = (4,5))
nd4

In [ ]:
nd4_mean = nd4.mean(axis = 1)
nd4_mean

In [ ]:
nd4 - nd4_mean

In [ ]:
nd4 - nd4_mean.reshape(4,1)

例2：
a = np.arange(3).reshape((3, 1))
b = np.arange(3)
求a+b

习题
a = np.ones((4, 1))
b = np.arange(4)
求a+b

## 六、ndarray的排序

小测验：
使用以上所学numpy的知识，对一个ndarray对象进行选择排序。  

def Sortn(x):  

代码越短越好

In [10]:
nd

NameError: name 'nd' is not defined

In [ ]:
np.sort(nd)

In [ ]:
nd.sort()

In [ ]:
nd

### 1. 快速排序
np.sort()与ndarray.sort()都可以，但有区别：
- np.sort()不改变输入
- ndarray.sort()本地处理，不占用空间，但改变输入

### 2. 部分排序
np.partition(a,k)

有的时候我们不是对全部数据感兴趣，我们可能只对最小或最大的一部分感兴趣。
- 当k为正时，我们想要得到最小的k个数
- 当k为负时，我们想要得到最大的k个数

In [ ]:
nd = np.random.randint(0,10000,size = 100)

In [ ]:
nd

In [ ]:
np.partition(nd,kth = 5)[:5]

In [ ]:
np.partition(nd,kth = -5)[-5:]

In [11]:
np.random.randint(0,2,size = 100)

array([1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0,
       1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0,
       0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0])